// ⚠️ automatisch generiert – nicht manuell bearbeiten
export type SuitShort = "S"|"H"|"D"|"C";
export type RankCode = "A"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"10"|"J"|"Q"|"K";
export const CARD_IMAGES: Record<string, number> = {
  "2C": require("../../assets/cards/2_of_clubs.png"),
  "2D": require("../../assets/cards/2_of_diamonds.png"),
  "2H": require("../../assets/cards/2_of_hearts.png"),
  "2S": require("../../assets/cards/2_of_spades.png"),
  "3C": require("../../assets/cards/3_of_clubs.png"),
  "3D": require("../../assets/cards/3_of_diamonds.png"),
  "3H": require("../../assets/cards/3_of_hearts.png"),
  "3S": require("../../assets/cards/3_of_spades.png"),
  "4C": require("../../assets/cards/4_of_clubs.png"),
  "4D": require("../../assets/cards/4_of_diamonds.png"),
  "4H": require("../../assets/cards/4_of_hearts.png"),
  "4S": require("../../assets/cards/4_of_spades.png"),
  "5C": require("../../assets/cards/5_of_clubs.png"),
  "5D": require("../../assets/cards/5_of_diamonds.png"),
  "5H": require("../../assets/cards/5_of_hearts.png"),
  "5S": require("../../assets/cards/5_of_spades.png"),
  "6C": require("../../assets/cards/6_of_clubs.png"),
  "6D": require("../../assets/cards/6_of_diamonds.png"),
  "6H": require("../../assets/cards/6_of_hearts.png"),
  "6S": require("../../assets/cards/6_of_spades.png"),
  "7C": require("../../assets/cards/7_of_clubs.png"),
  "7D": require("../../assets/cards/7_of_diamonds.png"),
  "7H": require("../../assets/cards/7_of_hearts.png"),
  "7S": require("../../assets/cards/7_of_spades.png"),
  "8C": require("../../assets/cards/8_of_clubs.png"),
  "8D": require("../../assets/cards/8_of_diamonds.png"),
  "8H": require("../../assets/cards/8_of_hearts.png"),
  "8S": require("../../assets/cards/8_of_spades.png"),
  "9C": require("../../assets/cards/9_of_clubs.png"),
  "9D": require("../../assets/cards/9_of_diamonds.png"),
  "9H": require("../../assets/cards/9_of_hearts.png"),
  "9S": require("../../assets/cards/9_of_spades.png"),
  "10C": require("../../assets/cards/10_of_clubs.png"),
  "10D": require("../../assets/cards/10_of_diamonds.png"),
  "10H": require("../../assets/cards/10_of_hearts.png"),
  "10S": require("../../assets/cards/10_of_spades.png"),
  "AC": require("../../assets/cards/ace_of_clubs.png"),
  "AD": require("../../assets/cards/ace_of_diamonds.png"),
  "AH": require("../../assets/cards/ace_of_hearts.png"),
  "AS": require("../../assets/cards/ace_of_spades.png"),
  "JC": require("../../assets/cards/jack_of_clubs.png"),
  "JD": require("../../assets/cards/jack_of_diamonds.png"),
  "JH": require("../../assets/cards/jack_of_hearts.png"),
  "JS": require("../../assets/cards/jack_of_spades.png"),
  "KC": require("../../assets/cards/king_of_clubs.png"),
  "KD": require("../../assets/cards/king_of_diamonds.png"),
  "KH": require("../../assets/cards/king_of_hearts.png"),
  "KS": require("../../assets/cards/king_of_spades.png"),
  "QC": require("../../assets/cards/queen_of_clubs.png"),
  "QD": require("../../assets/cards/queen_of_diamonds.png"),
  "QH": require("../../assets/cards/queen_of_hearts.png"),
  "QS": require("../../assets/cards/queen_of_spades.png"),
};
export const getImageByCode = (code: string) => CARD_IMAGES[code];